<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public $products = [
        [
            'code'                  => 'Br1',
            'name'               => 'Brush (short)',
            'desc'               => 'Brush (short)',
            'price'                 => 58,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => '1.jpg',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'Br2',
            'name'               => 'Brush (Long)',
            'description'               => 'Brush (Long)',
            'price'                 => 68,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => '2.jpg',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'Travel',
            'name'               => '7-Piece Travel Set',
            'description'               => 'Brush (Long)',
            'price'                 => 868,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'N001',
            'name'               => 'nRose (15 sachet)',
            'description'               => 'Brush (Long)',
            'price'                 => 194,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'N002',
            'name'               => 'nSlims (15 sachet)',
            'description'               => 'Brush (Long)',
            'price'                 => 238,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => '',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'novset2',
            'name'               => 'Essential Set (n1, n7, n8)',
            'description'               => null,
            'desc_cn'               => null,
            'price'                 => 711,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 3,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'NonBox',
            'name'               => 'n2 PACKAGE FOC travel size n5 n7 n8',
            'description'               => null,
            'desc_cn'               => null,
            'price'                 => 1594,
            'discount'              => 15,
            'category_id'           => 8,
            'shipping_quantity'     => 4,
            'image_1'               => '3.jpg',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'NonBox2',
            'name'               => 'n4 PACKAGE FOC travel size n5 n7 n8',
            'description'               => null,
            'desc_cn'               => null,
            'price'                 => 1594,
            'discount'              => 0,
            'category_id'           => 8,
            'shipping_quantity'     => 4,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R001',
            'name'               => 'n1 - D.A.F CRYSTAL SERUM I',
            'description'               => 'A bioactive essence that penetrates deeply into the skin, while providing a high amount of moisture to repair damaged cells effectively. It stimulates cell regeneration and reduces the appearance of wrinkles, leaving skin smooth and radiant.',
            'desc_cn'               => '高效滋润，深层保湿，生物活性精华素，能迅速深入皮肤，为衰竭细胞补充大量水分，促进细胞再生，能明显消除皱纹，让皮肤呈现嫩滑亮丽。</p>',
            'price'                 => 390,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => '4.jpg',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R002',
            'name'               => 'n2 - P.A.C ESSENCE II',
            'description'               => "An intensive conditioning, pore repairing essence that rebalances the skin's pH levels, regulates sebum production, reduces skin inflammation, eliminates acnes and scars, while providing firming effects.",
            'desc_cn'               => "深层调理，毛孔修复，平衡油性肤质，解脂抗炎，特效消除粉刺和暗疮，紧肤。",
            'price'                 => 332,
            'discount'              => 5,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => '5.jpg',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R003',
            'name'               => 'n3 - P.R.E WHITENING III',
            'description'               => "<p>Contains natural whitening and anti-oxidant properties to prevent the production of dark spots, while improving skin's elasticity and firmness; It repairs and moisturizes the skin, providing a fast and safe way to achieve whitening effects.</p>",
            'desc_cn'               => "<p>天然美白元素的结缔，抵制黑斑产生，高抗氧，提高皮肤弹性与紧致效果；除了提供保湿功能，也含极佳滋润及养颜功效能快速及安全的达至白皙及柔嫩效果，并且含有高效修复功能。</p>",
            'price'                 => 413,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R004',
            'name'               => 'n4 - 3R BOOSTER IV',
            'description'               => "<p>A bioactive essence that penetrates deeply into the skin, while providing a high amount of moisture to repair damaged cells effectively. It stimulates cell regeneration and reduces the appearance of wrinkles, leaving skin smooth and radiant.</p>",
            'desc_cn'               => "<p>使细胞加速重生，重整，增强细胞代谢，产生胶原蛋白，紧实，抗老，高抗氧，使细胞健康及充满活力，增添光泽细滑。</p>",
            'price'                 => 332,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ]
    ];

    public function run()
    {
        foreach ($this->products as $product) {
            Product::create($product);
        }
    }
}
