<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public $products = [
        [
            'code'                  => 'Br1',
            'name_en'               => 'Brush (short)',
            'name_cn'               => '刷子（短）',
            'desc_en'               => 'Brush (short)',
            'desc_cn'               => '刷子（短）',
            'price'                 => 58,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => '1.jpg',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'Br2',
            'name_en'               => 'Brush (Long)',
            'name_cn'               => '刷子（长）',
            'desc_en'               => 'Brush (Long)',
            'desc_cn'               => '刷子（长）',
            'price'                 => 68,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => '2.jpg',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'Travel',
            'name_en'               => '7-Piece Travel Set',
            'name_cn'               => '7支旅行套装',
            'desc_en'               => 'Brush (Long)',
            'desc_cn'               => '刷子（长）',
            'price'                 => 868,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'N001',
            'name_en'               => 'nRose (15 sachet)',
            'name_cn'               => 'nRose (15 包)',
            'desc_en'               => 'Brush (Long)',
            'desc_cn'               => '刷子（长）',
            'price'                 => 194,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'N002',
            'name_en'               => 'nSlims (15 sachet)',
            'name_cn'               => 'nSlims (15 包)',
            'desc_en'               => 'Brush (Long)',
            'desc_cn'               => '刷子（长）',
            'price'                 => 238,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => '',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'novset2',
            'name_en'               => 'Essential Set (n1, n7, n8)',
            'name_cn'               => 'Essential Set (n1, n7, n8)',
            'desc_en'               => null,
            'desc_cn'               => null,
            'price'                 => 711,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 3,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'NonBox',
            'name_en'               => 'n2 PACKAGE FOC travel size n5 n7 n8',
            'name_cn'               => 'n2 配套 送 旅行装 n5 n7 n8',
            'desc_en'               => null,
            'desc_cn'               => null,
            'price'                 => 1594,
            'discount'              => 15,
            'category_id'           => 8,
            'shipping_quantity'     => 4,
            'image_1'               => '3.jpg',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'NonBox2',
            'name_en'               => 'n4 PACKAGE FOC travel size n5 n7 n8',
            'name_cn'               => 'Set B - n4 配套 送 旅行装 n5 n7 n8',
            'desc_en'               => null,
            'desc_cn'               => null,
            'price'                 => 1594,
            'discount'              => 0,
            'category_id'           => 8,
            'shipping_quantity'     => 4,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R001',
            'name_en'               => 'n1 - D.A.F CRYSTAL SERUM I',
            'name_cn'               => 'n1 - D.A.F 水晶精华露',
            'desc_en'               => 'A bioactive essence that penetrates deeply into the skin, while providing a high amount of moisture to repair damaged cells effectively. It stimulates cell regeneration and reduces the appearance of wrinkles, leaving skin smooth and radiant.',
            'desc_cn'               => '高效滋润，深层保湿，生物活性精华素，能迅速深入皮肤，为衰竭细胞补充大量水分，促进细胞再生，能明显消除皱纹，让皮肤呈现嫩滑亮丽。</p>',
            'price'                 => 390,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => '4.jpg',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R002',
            'name_en'               => 'n2 - P.A.C ESSENCE II',
            'name_cn'               => 'n2 - P.A.C 晶萃',
            'desc_en'               => "An intensive conditioning, pore repairing essence that rebalances the skin's pH levels, regulates sebum production, reduces skin inflammation, eliminates acnes and scars, while providing firming effects.",
            'desc_cn'               => "深层调理，毛孔修复，平衡油性肤质，解脂抗炎，特效消除粉刺和暗疮，紧肤。",
            'price'                 => 332,
            'discount'              => 5,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => '5.jpg',
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R003',
            'name_en'               => 'n3 - P.R.E WHITENING III',
            'name_cn'               => 'n3 - P.R.E 天然美白霜',
            'desc_en'               => "<p>Contains natural whitening and anti-oxidant properties to prevent the production of dark spots, while improving skin's elasticity and firmness; It repairs and moisturizes the skin, providing a fast and safe way to achieve whitening effects.</p>",
            'desc_cn'               => "<p>天然美白元素的结缔，抵制黑斑产生，高抗氧，提高皮肤弹性与紧致效果；除了提供保湿功能，也含极佳滋润及养颜功效能快速及安全的达至白皙及柔嫩效果，并且含有高效修复功能。</p>",
            'price'                 => 413,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R004',
            'name_en'               => 'n4 - 3R BOOSTER IV',
            'name_cn'               => 'n4 - 3.R.焕丽精华',
            'desc_en'               => "<p>A bioactive essence that penetrates deeply into the skin, while providing a high amount of moisture to repair damaged cells effectively. It stimulates cell regeneration and reduces the appearance of wrinkles, leaving skin smooth and radiant.</p>",
            'desc_cn'               => "<p>使细胞加速重生，重整，增强细胞代谢，产生胶原蛋白，紧实，抗老，高抗氧，使细胞健康及充满活力，增添光泽细滑。</p>",
            'price'                 => 332,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R005',
            'name_en'               => 'n5 - 3 IN 1 CLEANSING MILK',
            'name_cn'               => 'n5 - 3合1 泡沫洁面乳',
            'desc_en'               => "<p>Highly moisturizing cleansing milk that delicately clean out pores while still nourishes the skin. It rebalances and soothes the skin. Can also be used as a make-up remover. Suitable for all skin types.</p>",
            'desc_cn'               => "<p>独特3合1配方有3种清洁功能，可用于洁面乳，泡沫洁面乳和卸妆乳，也可做为面膜使用。有效清除皮肤尘垢和日常化妆无皂基，温和配方对皮肤无刺激，不会导致皮肤干燥。可深层净洁及滋养肌肤，疏通阻塞毛孔，提供滋润，滋养，平衡，镇定功效。</p>",
            'price'                 => 217,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R007',
            'name_en'               => 'n7 - BIO-MIST',
            'name_cn'               => 'n7 - 活性提升喷雾',
            'desc_en'               => "<p>An anti-oxidant formula for cell restructuring and anti-aging conditions. It speed up the regeneration of cells, and stimulates the production of collagen while providing firming effects, leaving skin healthy and radiant.</p>",
            'desc_cn'               => "<p>特别配方，可使脸部和颈部恢复弹性，结实紧致，提升塑形效果，更能使皮肤美白及充满光泽亮丽。</p>",
            'price'                 => 252,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R008',
            'name_en'               => 'n8 - UV DEFENCE SPF 45',
            'name_cn'               => 'n8 - 防晒 SPF45',
            'desc_en'               => "<p>Protects skin from sun and harsh UVA/ UVB rays. It soothes and re-hydrates the skin, while covering up blemishes and brightens skin tone. &nbsp;</p>",
            'desc_cn'               => "<p>防晒以及对抗日光紫外线A&amp;B，提供皮肤滋润与舒缓，自然遮盖及掩饰皮肤瑕疵，使皮肤瞬间白皙亮丽。</p>",
            'price'                 => 263,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R009',
            'name_en'               => 'nE - EVERGLOW CARE',
            'name_cn'               => 'nE - 焕变霜',
            'desc_en'               => "<p>Able to effectively nourish and condition the skin to keep it moisturized. Meanwhile, it can repair damaged cells and improve the cell's immunity. After application, skin will look bright, moisturized and radiant.&nbsp;</p>",
            'desc_cn'               => "<p>拥有良好的润肤作用盒调湿效果，能让肌肤保持滋润。同时，可以修复外界对肌肤角质层的伤害，修复受损细胞，提高肌肤的抵抗力作用。使用后，可以使肌肤亮丽、滋润细致、自然晶莹。</p>",
            'price'                 => 459,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R010',
            'name_en'               => 'Luminous Oil (30ml)',
            'name_cn'               => '高抗氧修复油（30ml）',
            'desc_en'               => null,
            'desc_cn'               => null,
            'price'                 => 349,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R011',
            'name_en'               => 'The Lab Soothing Mask (5pcs)',
            'name_cn'               => 'The Lab 舒缓面膜 (5片)',
            'desc_en'               => null,
            'desc_cn'               => null,
            'price'                 => 168,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R012',
            'name_en'               => 'Miracle Anti-Oxidant Rose Oil (30ml)',
            'name_cn'               => '抗氧玫瑰油 (30ml)',
            'desc_en'               => null,
            'desc_cn'               => null,
            'price'                 => 339,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
        [
            'code'                  => 'R013',
            'name_en'               => 'Time Freeze Mask (10pcs)',
            'name_cn'               => 'Time Freeze Mask (10片)',
            'desc_en'               => null,
            'desc_cn'               => null,
            'price'                 => 198,
            'discount'              => 0,
            'category_id'           => 7,
            'shipping_quantity'     => 1,
            'image_1'               => null,
            'status'                => 'Active',
            'remarks'               => 'testing',
            'updated_at'            => null,
            'created_by'            => 1,
        ],
    ];

    public function run()
    {
        foreach ($this->products as $product) {
            Product::create($product);
        }
    }
}
